DEPOT_SEARCH_REFRESH_DEBOUNCE_MS = 250
DEPOT_VIEW_TTL_MS = 4000
DEPOT_RECENT_VIEW_TTL_MS = 5000

__all__ = [
    "DEPOT_RECENT_VIEW_TTL_MS",
    "DEPOT_SEARCH_REFRESH_DEBOUNCE_MS",
    "DEPOT_VIEW_TTL_MS",
]
